website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from .models import User, Task,  FinishedTask, Comment
from . import db
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from werkzeug.utils import secure_filename
import uuid as uuid
import os
from website import app

views = Blueprint("views", __name__)


@views.route("/")
def home():
    return render_template("home.html")


@views.route('/register')
def register():
    return render_template("register.html")


@views.route('/login')
def login():
    return render_template('login.html')


@views.route("/dashboard")
@login_required
def dashboard():
    tasks = Task.query.all()
    user = User.query.all()
    finished = FinishedTask.query.all()
    picture = current_user.picture
    tasks_length = len(tasks)
    if tasks_length == 0:
        redirect(url_for('views.dashboard', picture=picture))
    else:
        tasks = Task.query.all()
        user = User.query.all()
        finished = FinishedTask.query.all()
        picture = current_user.picture
        finished_task_length = len(finished)
        alltasks = tasks_length+finished_task_length
        task_percent = int((tasks_length/alltasks)*100)
        finished_percent = int((finished_task_length/alltasks)*100)
        return render_template("dashboard.html", user=user, alltasks=alltasks, tasks=tasks, finished=finished, picture=picture, task_percent=task_percent, finished_percent=finished_percent)


@views.route("/profile/<id>", methods=["POST", "GET"])
@login_required
def profile(id):
    profile = User.query.get_or_404(id)
    if request.method == "POST" and current_user:
        profile.username = request.form.get('username')
        profile.first_name = request.form.get('first_name')
        profile.last_name = request.form.get('last_name')
        profile.id = profile.id
        profile.job = request.form.get('job')
        profile.email = request.form.get('email')
        profile.password = generate_password_hash(
            request.form.get('password'), method="sha256")
        picture = request.files['picture']
        name = secure_filename(picture.filename)
        picture_name = str(uuid.uuid1())+"_"+name
        saved_file = request.files['picture']
        profile.picture = picture_name
        db.session.commit()
        saved_file.save(os.path.join(
            app.config['PROFILE_PICTURE_FOLDER'], picture_name))
        return redirect(url_for('views.profile', user=current_user, id=current_user.id))
    return render_template("profile.html", user=current_user, id=current_user.id)


@views.route("/projects", methods=["GET", "POST"])
@login_required
def project():
    return render_template("projects.html", user=current_user)


@views.route('/tasks', methods=["POST", "GET"])
@login_required
def tasks():
    task = Task.query

    if current_user and request.method == "POST":
        task.open_task = request.form.get("task")
        task.task_descriptif = request.form.get("task_descriptif")
        tasks = Task(open_task=task.open_task, ongoing_task=task.open_task,
                     operator=current_user.id, task_descriptif=task.task_descriptif)
        db.session.add(tasks)
        db.session.commit()
    return render_template("tasks.html", user=current_user, tasks=task)


@views.route('/finished/<id>', methods=['POST', "GET"])
@login_required
def finished(id):
    task = Task.query.filter_by(id=id).first()
    finished = FinishedTask.query.filter_by(id=id).first()
    finishedt = FinishedTask(finished_task=task.open_task,
                             finished_task_operator=task.operator, operator_username=task.user.username)
    db.session.add(finishedt)
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for("views.dashboard", task=task, finishedt=finished, user=current_user))


@views.route('/update/<id>', methods=["POST", "GET"])
@ login_required
def update(id):
    task = Task.query.get(id)
    if current_user and request.method == "POST":
        task.open_task = request.form["task_to_update"]
        task.ongoing_task = request.form['task_to_update']
        task.task_descriptif = request.form['task_descriptif_to_update']
        db.session.commit()
    return render_template("update.html", task=task)


@views.route('/delete/<id>', methods=["POST", "GET"])
@ login_required
def delete(id):
    task = Task.query.filter_by(id=id).first()
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for('views.dashboard', task=task))


@views.route('/delete_descriptif/<task_descriptif>', methods=["POST", "GET"])
@login_required
def delete_descriptif(task_descriptif):
    task = Task.query.filter_by(task_descriptif=task_descriptif).first()
    if task:
        db.session.delete(task)
        db.session.commit()
        flash("Task deleted successfully.")
    else:
        flash("Task not found.")

    return redirect(url_for('views.dashboard'))


@views.route("/projects/<username>")
@login_required
def projects(username):
    user = User.query.filter_by(username=username).first()
    task = user.task
    finishedtasks = FinishedTask.query.filter_by(
        finished_task_operator=current_user.id).all()
    return render_template("projects.html", user=current_user, task=task, finishedtasks=finishedtasks, username=username)


@views.route("/description/<task_id>", methods=["POST", "GET"])
@login_required
def description(task_id):
    tasks = Task.query.all()
    task = Task.query.filter_by(id=task_id).first()
    text_comment = request.form.get('comment')
    if text_comment is not None:
        comment = Comment(comment=text_comment,
                          operator=current_user.id, task_id=task_id)
        db.session.add(comment)
        db.session.commit()
    comments = Comment.query.all()
    return render_template("description.html", user=current_user, tasks=tasks, task=task,  comments=comments)


@views.route("/update_comment/<comment_id>", methods=["GET", "POST"])
@login_required
def update_comment(comment_id):
    comment = Comment.query.get(comment_id)
    if not comment:
        flash("comment does not exist")

    if comment.operator != current_user.id:
        flash("yout not allowed to modify this Comment")
    if request.method == "POST":
        new_comment = request.form.get("comment")
        comment.comment = new_comment
        db.session.commit()
        flash("Comment updated successfully.")
        return redirect(url_for("views.description", task_id=comment.task_id))
    return render_template("update_comment.html", task_id=comment.task_id)


@ views.route("/delete_comment/<comment_id>", methods=["GET", "POST"])
@ login_required
def delete_comment(comment_id):
    comment = Comment.query.get(comment_id)

    if comment.operator != current_user.id:
        flash("Comment was not deleted")

    if request.method == "POST":
        db.session.delete(comment)
        db.session.commit()
        flash("Comment deleted successfully.")
        return redirect(url_for("views.description", task_id=comment.task_id))
    return render_template("delete_comment.html", task_id=comment.task_id)


class SearchForm(FlaskForm):
    searched = StringField("Searched", validators=[DataRequired()])
    submit = SubmitField("Submit")


@ views.context_processor
def base():
    form = SearchForm()
    return dict(form=form)


@ views.route("/search_result", methods=["POST"])
@ login_required
def search_result():
    form = SearchForm()
    task = Task.query
    output_searched = form.searched.data
    search_result = task.filter(Task.open_task.like('%'+output_searched+"%"))
    search_result = search_result.order_by(Task.open_task).all()
    return render_template("search_result.html", user=current_user, output=output_searched, form=form, search_result=search_result)


@ views.route("/calendar")
@ login_required
def calendar():
    task = Task.query
    return render_template("calendar.html", user=current_user, task=task)


@ app.errorhandler(404)
def error(e):
    return render_template("404.html"), 404


@ app.errorhandler(500)
def internal_error(e):
    return render_template("500.html"), 500

website/templates/calendar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Dashboard</title>
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <link rel="shortcut icon" href="{{url_for('static',filename='/images/p.png')}}">
    <script defer type="text/javascript" src="{{url_for('static',filename='script.js')}}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"
        integrity="sha256-8EcfIJRWyvnu/U0OsfCk05x1JGVmeC2a7sJQHrbWYSA=" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container">
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{{url_for('static',filename='images/logo1.png')}}" alt="Logo" />

                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp"> close </span>
                </div>
            </div>

            <div class="sidebar">
                <a href="/dashboard" class="active">
                    <span class="material-icons-sharp"> dashboard </span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{url_for('views.description', task_id=current_user.id)}}">
                    <span class="material-icons-sharp">description</span>
                    <h3>Description</h3>
                </a>
                <a href="/calendar">
                    <span class="material-symbols-outlined">
                        calendar_month
                    </span>
                    <h3>Calendar</h3>
                </a>
                <a href="/projects/{{current_user.username}}">
                    <span class="material-icons-sharp">bar_chart</span>
                    <h3>Projects</h3>

                    <a href="/profile/{{current_user.id}}">
                        <span class="material-icons-sharp">account_circle</span>
                        <h3>Profile</h3>
                    </a>

                    <a href="/tasks">
                        <span class="material-icons-sharp"> add </span>
                        <h3>New task</h3>
                    </a>

                    <!-- <span class="material-icons-sharp" a href="/logout"> logout </span> -->
                    <a href="/logout"><span class="material-icons-sharp">logout</span>
                        <h3>logout</h3>
                    </a>

            </div>
        </aside>

        <main>
            <div class="search-bar">
                {{form.hidden_tag()}}
                <form action="{{url_for('views.search_result')}}" method="POST">
                    <input type="search" name="searched" placeholder="search for Task"><button type="submit"><span
                            class="material-icons-sharp">search</span></button>
                </form>
            </div>
            <h1>Dashboard</h1>
            <div class="date">
                <p id="date"></p>
            </div>
            <div class="wide">
                <div id="calendar"></div>
            </div>

        </main>
        <div class="right">
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons-sharp"> menu </span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons-sharp active" id='light'> light_mode </span>
                    <span class="material-icons-sharp" id='dark'> dark_mode </span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Hey, <b>{{current_user.username}}</b></p>

                    </div>
                    <div class="profile-photo">
                        {%if picture%}
                        <img class="profile_picture_bar"
                            src='{{url_for("static",filename="/images/profile_pictures/"+picture)}}' alt="">
                        {%else%}
                        <span class="material-icons-sharp">account_circle</span>
                        {%endif%}
                    </div>
                    {%if current_user.username=="admin"%}
                    <button><a href="/admin/">go to admin panel</a></button>
                    {%endif%}
                </div>
            </div>

            <div class="recent-updates">
                {%if current_user.username=="admin"%}
                <button><a href="/admin/">go to admin panel</a></button>
                {%endif%}
            </div>

        </div>
        <div class="wide">
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var calendarEl = document.getElementById('calendar');
                    var calendar = new FullCalendar.Calendar(calendarEl, {

                        initialView: 'dayGridMonth',
                        aspectRatio: 2,
                        events: [
                            {%for t in task %}
                            {
                            title: '{{ t.open_task }}',
                            start: '{{ t.date_created }}',
                        },
                        {% endfor %}
                    ]
                });
                calendar.updateSize();
                calendar.render();
                });
            </script>

        </div>
    </div>
    </div>
    </div>
    </div>


</body>

</html>
<div id="calendar">
</div>

website/templates/completed.html
<div class="income">
    <span class="material-icons-sharp">task_alt</span>
    <div class="middle">
        <div class="left">
            <h2>Completed Tasks</h2>
            {%for f in finished%}
            <h3>finished task: {{f.finished_task}}</h3>
            <h3>author: {{f.operator_username}}</h3>
            {%endfor%}
        </div>
        <div class="progres">
            <svg>
                <circle cx="38" cy="38" r="36" class="prog"></circle>
            </svg>
            <div class="number">
                <p>{{finished_percent}}%</p>
            </div>
        </div>
    </div>
    <small class="text-muted"> Last 24 hours </small>
</div>
<script>
    let progCircle = document.querySelector(".prog");
    let radial = progCircle.r.baseVal.value;
    let circ = radial * 2 * Math.PI;
    progCircle.style.strokeDasharray = circ;
    function setProgress(percent) {
        progCircle.style.strokeDashoffset =
            circ - (percent / 100) * circ;
    }
    setProgress("{{finished_percent}}")
</script>

website/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title> Dashboard</title>
  <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
  <link rel="shortcut icon" href="{{url_for('static',filename='/images/p.png')}}">
  <script defer type="text/javascript" src="{{url_for('static',filename='script.js')}}"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
</head>

<body>
  <div class="container">
    <aside>
      <div class="top">
        <div class="logo">
          <img src="{{url_for('static',filename='images/logo1.png')}}" alt="Logo" />

        </div>
        <div class="close" id="close-btn">
          <span class="material-icons-sharp"> close </span>
        </div>
      </div>

      <div class="sidebar">
        <a href="/dashboard" class="active">
          <span class="material-icons-sharp"> dashboard </span>
          <h3>Dashboard</h3>
        </a>
        <a href="{{url_for('views.description', task_id=current_user.id)}}">
          <span class="material-icons-sharp">description</span>
          <h3>Description</h3>
        </a>
        <a href="/calendar">
          <span class="material-symbols-outlined">
            calendar_month
          </span>
          <h3>Calendar</h3>
        </a>
        <a href="/projects/{{current_user.username}}">
          <span class="material-icons-sharp">bar_chart</span>
          <h3>Projects</h3>

          <a href="/profile/{{current_user.id}}">
            <span class="material-icons-sharp">account_circle</span>
            <h3>Profile</h3>
          </a>

          <a href="/tasks">
            <span class="material-icons-sharp"> add </span>
            <h3>New task</h3>
          </a>

          <!-- <span class="material-icons-sharp" a href="/logout"> logout </span> -->
          <a href="/logout"><span class="material-icons-sharp">logout</span>
            <h3>logout</h3>
          </a>

      </div>
    </aside>

    <main>
      <div class="search-bar">
        {{form.hidden_tag()}}
        <form action="{{url_for('views.search_result')}}" method="POST">
          <input type="search" name="searched" placeholder="search for Task"><button type="submit"><span
              class="material-icons-sharp">search</span></button>
        </form>
      </div>
      <h1>Dashboard</h1>

      <div class="date">
        <p id="date"></p>
      </div>
      <br>
      <br>
      <div class="wide">
        <div class="all">
          <div class="slider">
            <img src="{{url_for('static',filename='images/image.png')}}" alt="photo">
            <div class="text">
              <h1>Welcome to ProTask manager</h1>
              <br>
              <p>where you can manage your tasks easily.</p>
            </div>
          </div>
        </div>
        <br>
        <br>
        <div class="insights">
          <!-- open tasks -->
          {%include "open_task.html"%}
          <!-- in progress -->
          {%include "progress.html"%}
          <!-- completed task -->
          {%include "completed.html"%}


        </div>
        <div class="recent-tasks">
          <h2>Recent Tasks</h2>
          <table id="recent-tasks--table">
            <thead>
              <tr>
                <th>Project Name</th>
                <th>Task Name</th>
                <th>Hours</th>
                <th>Status</th>
                <th></th>
              </tr>
            </thead>
            {%for t in tasks%}
            <tr>
              <td><a href="/posts/{{t.user.username}}"
                  style="text-decoration: none; color:black; font-size: 18px; font-weight: bold;">{{t.user.username}}</a>
              </td>
              <td>
                <h4>{{t.open_task}}</h4>
              </td>
              <td> <a href="{{url_for('views.calendar')}}">{{t.task_descriptif}}</a> </td>
              <td>
                <p>{{t.date_created}}</p>
              </td>
            </tr>
            </thead>
            {%endfor%}
          </table>
          <a href="#">Show All</a>
        </div>

    </main>
    <div class="right">
      <div class="top">
        <button id="menu-btn">
          <span class="material-icons-sharp"> menu </span>
        </button>
        <div class="theme-toggler">
          <span class="material-icons-sharp active" id='light'> light_mode </span>
          <span class="material-icons-sharp" id='dark'> dark_mode </span>
        </div>
        <div class="profile">
          <div class="info">
            <p>Hey, <b>{{current_user.username}}</b></p>

          </div>
          <div class="profile-photo">
            {%if picture%}
            <img class="profile_picture_bar" src='{{url_for("static",filename="/images/profile_pictures/"+picture)}}'
              alt="">
            {%else%}
            <span class="material-icons-sharp">account_circle</span>
            {%endif%}
          </div>
          {%if current_user.username=="admin"%}
          <button><a href="/admin/">go to admin panel</a></button>
          {%endif%}
        </div>
      </div>

      <div class="recent-updates">
        {%if current_user.username=="admin"%}
        <button><a href="/admin/">go to admin panel</a></button>
        {%endif%}
      </div>

    </div>
  </div>
  </div>
  </div>
  </div>


</body>

</html>

website/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static',filename='/images/p.png')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    <title>Welcome to ProTask</title>
</head>

<body>
    <header>
        <nav>
            <img class="lg-hd" height=" 200px" src="{{url_for('static',filename='images/logo1.png')}}" alt="">
            <button class="btn-try"><a href="./register"
                    style="text-decoration:none; color:black;">Register</a></button>
        </nav>
        <section>
            <div class="build-comm">
                <h3>Construct And Organize Your Work With Ease With ProTask</h3>
                <p>ProTask is here to help you plannify and monitor your tasks progress. Helps with Teamwork and
                    establish order in daily work. </p>
                <button class="btn-start"><a href="/login" style="text-decoration:none;color:white;"> Sign in
                    </a></button>
            </div>
            <div>
                <img class="mockup" src="{{url_for('static',filename='images/illustration-intro.png')}}" alt="">
            </div>
        </section>
    </header>
    <main>
        <article class="article-sect">
            <div class="article-text">
                <h3>Grow Together</h3>
                <p>Efficiency is the key to success, and our task management app is here to help you unlock your full
                    potential. Create
                    tasks, set deadlines, and prioritize your work with ease.</p>
            </div>
            <img class="svgs" src="{{url_for('static',filename='images/undraw_accept_tasks_re_09mv.svg')}}" alt="">
        </article>
        <article class="article-sect reverse">
            <img class="svgs" src="{{url_for('static',filename='images/undraw_completed_tasks_vs6q.svg')}}" alt="">
            <div class="article-text">
                <h3>Flowing Conversations</h3>
                <p>Collaboration made simple! Our task management app enables you to share tasks with colleagues,
                    friends, or family
                    members effortlessly. Delegate responsibilities, track progress, and communicate effectively within
                    the app.</p>
            </div>
        </article>
        <article class="article-sect">
            <div class="article-text">
                <h3>Your Users</h3>
                <p>Our app allows you to break down complex projects into smaller, manageable subtasks, ensuring you
                    stay on top of your
                    workload.</p>
            </div>
            <img class="svgs" src="{{url_for('static',filename='images/undraw_task_list_6x9d.svg')}}" alt="">
        </article>
    </main>
    <footer>

        <div class=" ft-sct">
            <div class="ft-part">
                <img class="lg-ft" src="{{url_for('static',filename='images/logo1.png')}}" alt="">
                <div class="ft-loc">
                    <img height="20px" src="./images/icon-location.svg" alt="">
                    <p>Lorem ipsum dolor, sit amet consectetur
                    </p>
                </div>
                <div class="ft-loc">
                    <img src="./images/icon-phone.svg" alt="">
                    <p>+1-543-123-4567</p>
                </div>
                <div class="ft-loc">
                    <img src="./images/icon-email.svg" alt="">
                    <p>example@huddle.com</p>
                </div>
            </div>
            <div class="ft-part">
                <p>About us</p>
                <p>What We Do</p>
                <p>FAQ</p>

            </div>
            <div class="ft-part">
                <p>Carrer</p>
                <p>Blog</p>
                <p>Contact Us</p>
            </div>


        </div>
    </footer>
</body>

</html>

website/templates/search_result.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Dashboard</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='/images/p.png')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <script defer type="text/javascript" src="{{url_for('static',filename='script.js')}}"></script>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
</head>

<body>
    <div class="container">
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{{url_for('static',filename='images/logo1.png')}}" alt="Logo" />

                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp"> close </span>
                </div>
            </div>

            <div class="sidebar">
                <a href="/dashboard" class="active">
                    <span class="material-icons-sharp"> dashboard </span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{url_for('views.description', task_id=current_user.id)}}">
                    <span class="material-icons-sharp">description</span>
                    <h3>Description</h3>
                </a>
                <a href="/calendar">
                    <span class="material-symbols-outlined">
                        calendar_month
                    </span>
                    <h3>Calendar</h3>
                </a>
                <a href="/projects/{{current_user.username}}">
                    <span class="material-icons-sharp">bar_chart</span>
                    <h3>Projects</h3>
                </a>

                <a href="/profile/{{current_user.id}}">
                    <span class="material-icons-sharp">account_circle</span>
                    <h3>Profile</h3>
                </a>

                <a href="/tasks">
                    <span class="material-icons-sharp"> add </span>
                    <h3>New task</h3>
                </a>

                <!-- <span class="material-icons-sharp" a href="/logout"> logout </span> -->
                <a href="/logout"><span class="material-icons-sharp">logout</span>
                    <h3>logout</h3>
                </a>

            </div>
        </aside>

        <main>
            <div class="search-bar">
                {{form.hidden_tag()}}
                <form action="{{url_for('views.search_result')}}" method="POST">
                    <input type="search" name="searched" placeholder="search for Task"><button type="submit"><span
                            class="material-icons-sharp">search</span></button>
                </form>
            </div>
            <h1>Dashboard</h1>

            <div class="date">
                <p id="date"></p>
            </div>
            <br>
            <br>
            <div class="all">
                <div class="slider">
                    <img src="{{url_for('static',filename='images/image.png')}}" alt="photo">
                    <div class="text">
                        <h1>Welcome to ProTask manager</h1>
                        <br>
                        <p>where you can manage your tasks easily.</p>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <div class="insights">


                <br />
                <br />
                <h2>You Searched For ...</h2>
                <h2>{{ output }}</h2>

                {% for r in search_result %}
                <br />
                the user: {{ r.user.username }}
                <br />
                the post: {{r.open_task}}
                <br />
                date creation: {{ r.date_created.strftime('%m/%d/%Y %I:%M %p') }}
                <br />
                {% endfor %}

                {% if output not in search_result %}
                <p>This Data or User doesn't exist</p>
                {% endif %}
            </div>
        </main>
        <div class="right">
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons-sharp"> menu </span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons-sharp active" id='light'> light_mode </span>
                    <span class="material-icons-sharp" id='dark'> dark_mode </span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Hey, <b>{{current_user.username}}</b></p>

                    </div>
                    <div class="profile-photo">
                        {%if user.picture%}
                        <div class="profile-photo">
                            <img class="profile_picture_bar"
                                src='{{url_for("static",filename="/images/profile_pictures/"+user.picture)}}' alt="">
                            {%else%}
                            <span class="material-icons-sharp">account_circle</span>
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>

</html>